In [2]:
import sys
import pandas as pd
from pathlib import Path
sys.path.append(str(Path().resolve().parent))
from src.unificacion import path_file
# from src.procesamiento_individual import main_individual_a, main_individual_b

path_file_merge_individual = path_file('merge_individual.csv')
path_file_merge_hogar = path_file('merge_hogar.csv')

In [3]:
df_individual = pd.read_csv(path_file_merge_individual,delimiter=";",encoding="utf-8", low_memory=False)

In [4]:
df_individual.shape

(46050, 181)

In [5]:
personas_aptas = df_individual[(df_individual.CH06 >= 18) & (df_individual.ESTADO > 0) & (df_individual.ESTADO < 3)]

personas_aptas_v2 = df_individual[df_individual.ESTADO.isin([1,2])]

personas_aptas_v3 = df_individual[(df_individual.CH06 >= 18) & (df_individual.ESTADO.isin([1,2]))]

In [6]:
df_individual.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46050 entries, 0 to 46049
Columns: 181 entries, CODUSU to UNIVERSITARIO
dtypes: float64(105), int64(67), object(9)
memory usage: 63.6+ MB

In [7]:
df_individual.CH06.info()
print("/"*20)
df_individual.PP07G2.info()

<class 'pandas.core.series.Series'>
RangeIndex: 46050 entries, 0 to 46049
Series name: CH06
Non-Null Count  Dtype
--------------  -----
46050 non-null  int64
dtypes: int64(1)
memory usage: 359.9 KB
////////////////////
<class 'pandas.core.series.Series'>
RangeIndex: 46050 entries, 0 to 46049
Series name: PP07G2
Non-Null Count  Dtype
--------------  -----
20325 non-null  float64
dtypes: float64(1)
memory usage: 359.9 KB

In [8]:
print(personas_aptas.info())
print(personas_aptas.shape)
print("/ /"*20)
print(personas_aptas_v2.info())
print(personas_aptas_v2.shape)

# print(personas_aptas_v3.shape)

<class 'pandas.core.frame.DataFrame'>
Index: 21583 entries, 0 to 46045
Columns: 181 entries, CODUSU to UNIVERSITARIO
dtypes: float64(105), int64(67), object(9)
memory usage: 30.0+ MB
None
(21583, 181)
/ // // // // // // // // // // // // // // // // // // // /
<class 'pandas.core.frame.DataFrame'>
Index: 21687 entries, 0 to 46045
Columns: 181 entries, CODUSU to UNIVERSITARIO
dtypes: float64(105), int64(67), object(9)
memory usage: 30.1+ MB
None
(21687, 181)

# se continua

In [9]:
df_individual

,CODUSU,ANO4,TRIMESTRE,NRO_HOGAR,COMPONENTE,H15,REGION,MAS_500,AGLOMERADO,PONDERA,...,IDECCFR,RDECCFR,GDECCFR,PDECCFR,ADECCFR,PONDIH,CH04_str,NIVEL_ED_str,CONDICION_LABORAL,UNIVERSITARIO
0,TQRMNOPUTHLMKQCDEGGFB00852588,2024,1,1,3,1,42,S,10,439,...,12.0,12,12.0,NaN,12,0,Femenino,Secundario incompleto,Ocupado dependiente,0
1,TQRMNOPUTHLMKQCDEGGFB00852588,2024,1,1,4,1,42,S,10,439,...,12.0,12,12.0,NaN,12,0,Femenino,Superior o universitario,Inactivo,0
2,TQRMNOPUTHLMKQCDEGGFB00852588,2024,1,1,5,0,42,S,10,439,...,12.0,12,12.0,NaN,12,0,Femenino,Sin informacion,Fuera de categoría/sin información,2
3,TQRMNOPPWHLLKRCDEGGFB00852574,2024,1,1,1,1,42,S,10,675,...,6.0,6,6.0,NaN,6,1610,Masculino,Secundario completo,Ocupado dependiente,0
4,TQRMNOPPWHLLKRCDEGGFB00852574,2024,1,1,2,1,42,S,10,675,...,6.0,6,6.0,NaN,6,1610,Femenino,Secundario completo,Ocupado dependiente,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46045,TQRMNOPUQHKMKNCDEIJAH00861661,2024,1,1,1,1,1,S,33,3410,...,NaN,12,12.0,NaN,12,0,Femenino,Secundario incompleto,Ocupado dependiente,0
46046,TQRMNOPUQHKMKNCDEIJAH00861661,2024,1,1,2,2,1,S,33,3410,...,NaN,12,12.0,NaN,12,0,Masculino,Secundario incompleto,Sin datos válidos,0
46047,TQRMNOPUQHKMKNCDEIJAH00861661,2024,1,1,3,2,1,S,33,3410,...,NaN,12,12.0,NaN,12,0,Masculino,Secundario incompleto,Sin datos válidos,0
46048,TQRMNOPUQHKMKNCDEIJAH00861661,2024,1,1,4,2,1,S,33,3410,...,NaN,12,12.0,NaN,12,0,Masculino,Secundario incompleto,Sin datos válidos,2
46049,TQRMNOPUQHKMKNCDEIJAH00861661,2024,1,1,5,2,1,S,33,3410,...,NaN,12,12.0,NaN,12,0,Femenino,Superior o universitario,Sin datos válidos,0

In [10]:
# filtro por personas que estan entre ocupadas y desocupadas
def filter_by_employment_status(df: pd.DataFrame) -> pd.DataFrame :
    return df[df.ESTADO.isin([1,2])]

In [11]:
df_individual["ESTADO"] = df_individual["ESTADO"].astype(int)

In [12]:
df_individual_aptos = filter_by_employment_status(df_individual)

In [13]:
df_individual_aptos

,CODUSU,ANO4,TRIMESTRE,NRO_HOGAR,COMPONENTE,H15,REGION,MAS_500,AGLOMERADO,PONDERA,...,IDECCFR,RDECCFR,GDECCFR,PDECCFR,ADECCFR,PONDIH,CH04_str,NIVEL_ED_str,CONDICION_LABORAL,UNIVERSITARIO
0,TQRMNOPUTHLMKQCDEGGFB00852588,2024,1,1,3,1,42,S,10,439,...,12.0,12,12.0,NaN,12,0,Femenino,Secundario incompleto,Ocupado dependiente,0
3,TQRMNOPPWHLLKRCDEGGFB00852574,2024,1,1,1,1,42,S,10,675,...,6.0,6,6.0,NaN,6,1610,Masculino,Secundario completo,Ocupado dependiente,0
4,TQRMNOPPWHLLKRCDEGGFB00852574,2024,1,1,2,1,42,S,10,675,...,6.0,6,6.0,NaN,6,1610,Femenino,Secundario completo,Ocupado dependiente,0
5,TQRMNOPPWHLLKRCDEGGFB00852574,2024,1,1,3,1,42,S,10,675,...,6.0,6,6.0,NaN,6,1610,Femenino,Superior o universitario,Ocupado dependiente,1
6,TQRMNOPPWHLLKRCDEGGFB00852574,2024,1,1,4,1,42,S,10,675,...,6.0,6,6.0,NaN,6,1610,Masculino,Superior o universitario,Ocupado dependiente,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46040,TQRMNOPSYHJLOQCDEIIAD00794774,2024,1,1,1,1,1,S,32,1376,...,NaN,10,10.0,NaN,10,1781,Femenino,Superior o universitario,Ocupado dependiente,0
46042,TQRMNOSXVHJKKMCDEIJAH00794775,2024,1,1,2,1,1,S,33,2818,...,NaN,12,12.0,NaN,12,0,Masculino,Secundario completo,Desocupado,0
46043,TQRMNOSXVHJKKMCDEIJAH00794775,2024,1,1,3,1,1,S,33,2818,...,NaN,12,12.0,NaN,12,0,Masculino,Superior o universitario,Ocupado dependiente,1
46044,TQRMNOSXVHJKKMCDEIJAH00794775,2024,1,1,4,1,1,S,33,2818,...,NaN,12,12.0,NaN,12,0,Femenino,Superior o universitario,Ocupado dependiente,1
46045,TQRMNOPUQHKMKNCDEIJAH00861661,2024,1,1,1,1,1,S,33,3410,...,NaN,12,12.0,NaN,12,0,Femenino,Secundario incompleto,Ocupado dependiente,0

In [14]:
len(df_individual["CH06"])

46050

In [15]:
df_individual_aptos["CH06"].notnull().sum()

np.int64(21687)

In [16]:
df_individual["CH06"].isnull().sum()

np.int64(0)

In [17]:
df_individual["ESTADO"].value_counts()

ESTADO
1    20325
3    18724
4     5558
2     1362
0       81
Name: count, dtype: int64

In [41]:
df_aglomerado_aptos = df_individual_aptos.groupby("AGLOMERADO")["PONDERA"].sum().reset_index(name="PEA")

In [42]:
df_aglomerado_aptos

    AGLOMERADO      PEA
0            2   476764
1            3   154152
2            4   656871
3            5   248877
4            6   131294
5            7   191878
6            8   196607
7            9   100212
8           10   525774
9           12   170665
10          13   800391
11          14    67344
12          15   109504
13          17   163565
14          18   187155
15          19   174122
16          20    58063
17          22   106883
18          23   303837
19          25   107631
20          26   114460
21          27   246581
22          29   414746
23          30    64949
24          31    88841
25          32  1615954
26          33  6125409
27          34   330189
28          36    80730
29          38    81807
30          91    70985
31          93    35930

In [38]:
df_aglomerado_aptos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   AGLOMERADO  32 non-null     int64
 1   PEA         32 non-null     int64
dtypes: int64(2)
memory usage: 644.0 bytes

In [39]:
ocupados = df_individual_aptos[df_individual_aptos["ESTADO"] == 1].groupby("AGLOMERADO")["PONDERA"].sum().reset_index(name="OCUPADOS")

In [40]:
ocupados

    AGLOMERADO  OCUPADOS
0            2    437461
1            3    142612
2            4    620218
3            5    229846
4            6    125813
5            7    182322
6            8    182413
7            9     97440
8           10    500788
9           12    157867
10          13    739501
11          14     64490
12          15    106388
13          17    153090
14          18    182449
15          19    159945
16          20     56745
17          22    102733
18          23    286780
19          25    102200
20          26    110454
21          27    235554
22          29    381867
23          30     60151
24          31     83873
25          32   1529661
26          33   5516390
27          34    310699
28          36     78004
29          38     74656
30          91     66225
31          93     35293

In [32]:
desocupados = df_individual_aptos[df_individual_aptos["ESTADO"] == 2].groupby("AGLOMERADO")["PONDERA"].sum().reset_index(name="DESOCUPADOS")

In [33]:
desocupados

    AGLOMERADO  DESOCUPADOS
0            2        39303
1            3        11540
2            4        36653
3            5        19031
4            6         5481
5            7         9556
6            8        14194
7            9         2772
8           10        24986
9           12        12798
10          13        60890
11          14         2854
12          15         3116
13          17        10475
14          18         4706
15          19        14177
16          20         1318
17          22         4150
18          23        17057
19          25         5431
20          26         4006
21          27        11027
22          29        32879
23          30         4798
24          31         4968
25          32        86293
26          33       609019
27          34        19490
28          36         2726
29          38         7151
30          91         4760
31          93          637

In [34]:
pea_subdividido = pd.merge(ocupados,desocupados,on="AGLOMERADO")

In [36]:
pea_subdividido["PEA"] = pea_subdividido.apply(lambda x: x.OCUPADOS + x.DESOCUPADOS, axis= 1 )

In [37]:
pea_subdividido

    AGLOMERADO  OCUPADOS  DESOCUPADOS      PEA
0            2    437461        39303   476764
1            3    142612        11540   154152
2            4    620218        36653   656871
3            5    229846        19031   248877
4            6    125813         5481   131294
5            7    182322         9556   191878
6            8    182413        14194   196607
7            9     97440         2772   100212
8           10    500788        24986   525774
9           12    157867        12798   170665
10          13    739501        60890   800391
11          14     64490         2854    67344
12          15    106388         3116   109504
13          17    153090        10475   163565
14          18    182449         4706   187155
15          19    159945        14177   174122
16          20     56745         1318    58063
17          22    102733         4150   106883
18          23    286780        17057   303837
19          25    102200         5431   107631
20          26    110454         4006   114460
21          27    235554        11027   246581
22          29    381867        32879   414746
23          30     60151         4798    64949
24          31     83873         4968    88841
25          32   1529661        86293  1615954
26          33   5516390       609019  6125409
27          34    310699        19490   330189
28          36     78004         2726    80730
29          38     74656         7151    81807
30          91     66225         4760    70985
31          93     35293          637    35930

In [27]:
total_pea = df_individual_aptos.groupby("AGLOMERADO")["PONDERA"].sum()

In [28]:
total_pea

AGLOMERADO
2      476764
3      154152
4      656871
5      248877
6      131294
7      191878
8      196607
9      100212
10     525774
12     170665
13     800391
14      67344
15     109504
17     163565
18     187155
19     174122
20      58063
22     106883
23     303837
25     107631
26     114460
27     246581
29     414746
30      64949
31      88841
32    1615954
33    6125409
34     330189
36      80730
38      81807
91      70985
93      35930
Name: PONDERA, dtype: int64